name: nn_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - matplotlib
  - pip
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  - pandas
  - opencv
  - pillow
  - ipykernel
  - ipywidgets
  - ipython
  - pip:
      - tensorflow
      - torch
      - torchvision
      - torchaudio
      - keras-cv
      - umap-learn

